### ISSUE TITLE
ImportError: cannot import name '_helpers' from 'google.cloud.logging'

### ISSUE THREAD

**Issue by kaushalringle** [snickell/google_structlog#5]
Please can someone help me to resolve this issue. Here is the description of the error.  @snickell  @petzeb 

I am trying this in a virtual environment using pipenv. Maybe I am doing something wrong, please any help is greatly appreciated. 

**Error** 
```
>>> from google_structlog import getLogger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/__init__.py", line 1, in <module>
    from .setup import getLogger, setup, setup_stdout_logger, setup_google_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup.py", line 3, in <module>
    from .setup_stdout import setup_stdout_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_stdout.py", line 4, in <module>
    from .setup_google import get_default_logging_namespace
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_google.py", line 2, in <module>
    from google.cloud.logging import _helpers
ImportError: cannot import name '_helpers' from 'google.cloud.logging' (/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google/cloud/logging/__init__.py)

>>> import google_structlog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/__init__.py", line 1, in <module>
    from .setup import getLogger, setup, setup_stdout_logger, setup_google_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup.py", line 3, in <module>
    from .setup_stdout import setup_stdout_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_stdout.py", line 4, in <module>
    from .setup_google import get_default_logging_namespace
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_google.py", line 2, in <module>
    from google.cloud.logging import _helpers
ImportError: cannot import name '_helpers' from 'google.cloud.logging' (/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google/cloud/logging/__init__.py)

```

**Steps to reproduce** 
```
pipenv --three 

pipenv shell

(test-google-struct) ➜ pip install google_structlog

(test-google-struct) ➜ pip list
Package                  Version
------------------------ ---------
cachetools               4.2.1
certifi                  2020.12.5
chardet                  4.0.0
google-api-core          1.25.1
google-auth              1.24.0
google-cloud-core        1.5.0
google-cloud-logging     2.2.0
google-structlog         43.11.173
googleapis-common-protos 1.52.0
grpcio                   1.35.0
idna                     2.10
pip                      20.3.3
proto-plus               1.13.0
protobuf                 3.14.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
python-json-logger       2.0.1
pytz                     2020.5
requests                 2.25.1
rsa                      4.7
setuptools               51.3.3
six                      1.15.0
structlog                20.2.0
urllib3                  1.26.3
wheel                    0.36.2

(test-google-struct) ➜  python
Python 3.8.7 (default, Jan 29 2021, 10:47:44)
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from google_structlog import getLogger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/__init__.py", line 1, in <module>
    from .setup import getLogger, setup, setup_stdout_logger, setup_google_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup.py", line 3, in <module>
    from .setup_stdout import setup_stdout_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_stdout.py", line 4, in <module>
    from .setup_google import get_default_logging_namespace
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_google.py", line 2, in <module>
    from google.cloud.logging import _helpers
ImportError: cannot import name '_helpers' from 'google.cloud.logging' (/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google/cloud/logging/__init__.py)

>>> import google_structlog
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/__init__.py", line 1, in <module>
    from .setup import getLogger, setup, setup_stdout_logger, setup_google_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup.py", line 3, in <module>
    from .setup_stdout import setup_stdout_logger
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_stdout.py", line 4, in <module>
    from .setup_google import get_default_logging_namespace
  File "/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google_structlog/setup_google.py", line 2, in <module>
    from google.cloud.logging import _helpers
ImportError: cannot import name '_helpers' from 'google.cloud.logging' (/Users/user1/.local/share/virtualenvs/test-google-struct-MQ6U8Jne/lib/python3.8/site-packages/google/cloud/logging/__init__.py)



```

**Comment by rakeshmukundan** [comment]
I had the same issue, looks like cloud logger has updated it's APIs. created https://github.com/snickell/google_structlog/pull/6 to fix
